name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *" # Run every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-22.04 # Use explicit Ubuntu version
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate GitHub Contribution Grid Snake
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: overist
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      # Push generated SVGs to the output branch
      - name: Push GitHub Contribution Grid Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
