name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *" # Run every 24 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generate a snake game SVG from GitHub contributions graph
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: overist
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push generated SVG to output branch
      - name: Push GitHub Contribution Grid Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
